In [14]:
import numpy as np
arr1= np.random.rand(100)
arr2 = np.random.rand(100)

In [28]:
arr=[arr1,arr2]

In [29]:
arr

[array([4.64916594e-01, 6.66555803e-01, 1.82800427e-01, 3.19240334e-01,
        5.12692679e-01, 2.83482711e-01, 1.78971384e-01, 7.79911931e-01,
        4.77279527e-01, 6.83736511e-01, 8.79047718e-01, 7.79574474e-01,
        3.21742715e-01, 7.94015115e-01, 6.23668585e-01, 9.67279469e-01,
        5.98798576e-01, 2.12804754e-01, 1.91534640e-02, 1.70954189e-01,
        3.87874826e-01, 6.39466628e-02, 1.25505174e-01, 7.63029728e-01,
        1.28505334e-01, 3.43274976e-01, 7.30274838e-02, 2.29114908e-01,
        6.21497588e-01, 4.48247117e-01, 3.95511549e-01, 7.72007117e-01,
        6.68281419e-01, 6.01145800e-01, 9.26301858e-03, 6.22939201e-02,
        9.57684034e-01, 4.22102898e-01, 1.25760218e-01, 5.44771476e-01,
        2.04540073e-01, 7.18636872e-01, 1.86414931e-02, 3.19858350e-01,
        1.74730126e-01, 8.42027854e-01, 5.55643556e-01, 9.35281687e-01,
        2.61336604e-01, 9.65674889e-01, 9.58224871e-01, 6.02213218e-01,
        9.42524292e-01, 5.65725369e-02, 2.36932359e-04, 2.202573

In [33]:
from sklearn.preprocessing import normalize
barr,norm = normalize(arr,return_norm=True,axis=0)

In [34]:
barr

array([[0.66262929, 0.9967916 , 0.20314476, 0.60438645, 0.46584682,
        0.60286402, 0.55866142, 0.75358021, 0.86383405, 0.71768175,
        0.66683348, 0.99786307, 0.96537805, 0.80201942, 0.91209953,
        0.90622555, 0.93146718, 0.5546583 , 0.26410191, 0.28849011,
        0.37655385, 0.19759615, 0.1327768 , 0.99048074, 0.15425716,
        0.56028751, 0.14980973, 0.45327662, 0.92783244, 0.42551473,
        0.86656754, 0.6609464 , 0.99696647, 0.99713382, 0.02365948,
        0.16681047, 0.99654112, 0.82485105, 0.30811882, 0.49354636,
        0.34505562, 0.99623678, 0.10117194, 0.61470178, 0.89893498,
        0.83443884, 0.66619765, 0.89238117, 0.49708196, 0.87115521,
        0.79301566, 0.68578243, 0.99793113, 0.06279495, 0.00334891,
        0.25455503, 0.81688584, 0.85585868, 0.14158008, 0.09430669,
        0.30454625, 0.76341097, 0.52452218, 0.86665518, 0.54122834,
        0.72586545, 0.12077157, 0.6794798 , 0.70481316, 0.47592519,
        0.75288073, 0.99066985, 0.05029344, 0.28

In [35]:
barr*norm

array([[4.64916594e-01, 6.66555803e-01, 1.82800427e-01, 3.19240334e-01,
        5.12692679e-01, 2.83482711e-01, 1.78971384e-01, 7.79911931e-01,
        4.77279527e-01, 6.83736511e-01, 8.79047718e-01, 7.79574474e-01,
        3.21742715e-01, 7.94015115e-01, 6.23668585e-01, 9.67279469e-01,
        5.98798576e-01, 2.12804754e-01, 1.91534640e-02, 1.70954189e-01,
        3.87874826e-01, 6.39466628e-02, 1.25505174e-01, 7.63029728e-01,
        1.28505334e-01, 3.43274976e-01, 7.30274838e-02, 2.29114908e-01,
        6.21497588e-01, 4.48247117e-01, 3.95511549e-01, 7.72007117e-01,
        6.68281419e-01, 6.01145800e-01, 9.26301858e-03, 6.22939201e-02,
        9.57684034e-01, 4.22102898e-01, 1.25760218e-01, 5.44771476e-01,
        2.04540073e-01, 7.18636872e-01, 1.86414931e-02, 3.19858350e-01,
        1.74730126e-01, 8.42027854e-01, 5.55643556e-01, 9.35281687e-01,
        2.61336604e-01, 9.65674889e-01, 9.58224871e-01, 6.02213218e-01,
        9.42524292e-01, 5.65725369e-02, 2.36932359e-04, 2.202573

In [36]:
arr

[array([4.64916594e-01, 6.66555803e-01, 1.82800427e-01, 3.19240334e-01,
        5.12692679e-01, 2.83482711e-01, 1.78971384e-01, 7.79911931e-01,
        4.77279527e-01, 6.83736511e-01, 8.79047718e-01, 7.79574474e-01,
        3.21742715e-01, 7.94015115e-01, 6.23668585e-01, 9.67279469e-01,
        5.98798576e-01, 2.12804754e-01, 1.91534640e-02, 1.70954189e-01,
        3.87874826e-01, 6.39466628e-02, 1.25505174e-01, 7.63029728e-01,
        1.28505334e-01, 3.43274976e-01, 7.30274838e-02, 2.29114908e-01,
        6.21497588e-01, 4.48247117e-01, 3.95511549e-01, 7.72007117e-01,
        6.68281419e-01, 6.01145800e-01, 9.26301858e-03, 6.22939201e-02,
        9.57684034e-01, 4.22102898e-01, 1.25760218e-01, 5.44771476e-01,
        2.04540073e-01, 7.18636872e-01, 1.86414931e-02, 3.19858350e-01,
        1.74730126e-01, 8.42027854e-01, 5.55643556e-01, 9.35281687e-01,
        2.61336604e-01, 9.65674889e-01, 9.58224871e-01, 6.02213218e-01,
        9.42524292e-01, 5.65725369e-02, 2.36932359e-04, 2.202573

In [37]:
from dbanalysis import stop_tools


In [2]:
from dbanalysis import stop_tools
d=stop_tools.random_stop_data()

In [40]:
from sklearn.preprocessing import normalize

In [3]:
d.columns

Index(['index', 'dayofservice', 'tripid', 'plannedtime_arr_from',
       'plannedtime_dep_from', 'actualtime_arr_from', 'actualtime_dep_from',
       'plannedtime_arr_to', 'actualtime_arr_to', 'routeid', 'fromstop',
       'tostop', 'traveltime', 'dwelltime', 'distance', 'speed', 'dt', 'date',
       'day', 'month', 'hour', 'year', 'dewpt', 'msl', 'rain', 'rhum', 'temp',
       'vappr', 'wetb'],
      dtype='object')

In [9]:
from sklearn.preprocessing import normalize
import pandas as pd

In [7]:
nomrmed,norm = normalize(d[['day','month','hour','actualtime_arr_from','traveltime']],return_norm=True)

In [10]:
df = pd.DataFrame(nomrmed,columns = ['day','month','hour','actualtime_arr_from','traveltime'])

In [13]:
from sklearn.linear_model import LinearRegression as lr
rgr = lr().fit(df[['day','month','hour','actualtime_arr_from']],df['traveltime'])

In [14]:
preds = rgr.predict(df[['day','month','hour','actualtime_arr_from']])
from sklearn.metrics import r2_score
r2_score(df['traveltime'],preds)

0.9186990884134889

In [15]:
r2_score(d['traveltime'],preds*norm)

0.918815458763214

In [ ]:
preds*norm

## Ok so it does work. Kind of. Why isn't it working in my fucking model?

In [54]:
b[0:,0]*norm

array([60313., 60495., 60974., ..., 82555., 77436., 51703.])

In [56]:
print('hello')

hello


In [58]:
d.columns

Index(['index', 'dayofservice', 'tripid', 'plannedtime_arr_from',
       'plannedtime_dep_from', 'actualtime_arr_from', 'actualtime_dep_from',
       'plannedtime_arr_to', 'actualtime_arr_to', 'routeid', 'fromstop',
       'tostop', 'traveltime', 'dwelltime', 'distance', 'speed', 'dt', 'date',
       'day', 'month', 'hour', 'year', 'dewpt', 'msl', 'rain', 'rhum', 'temp',
       'vappr', 'wetb'],
      dtype='object')

In [75]:
features=['day', 'month', 'hour', 'year', 'dewpt', 'msl', 'rain', 'rhum', 'temp',
    'vappr', 'wetb']

In [76]:
a,norm = normalize(d[features+['traveltime']],return_norm=True)

In [67]:
import pandas as pd

In [77]:
df = pd.DataFrame(a,columns = features+['traveltime'])

In [78]:
d['traveltime']

0        45
1        42
2        49
3        53
4        51
5        52
6        47
7        39
8        44
9        45
10       47
11       49
12       43
13       35
14       40
15       40
16       50
17       51
18       43
19       39
20       42
21       40
22       42
23       39
24       40
25       51
26       43
27       42
28       47
29       46
         ..
11175    45
11176    40
11177    47
11178    49
11179    49
11180    50
11181    49
11182    46
11183    55
11184    51
11185    50
11186    49
11187    55
11188    47
11189    46
11190    51
11191    51
11192    44
11193    53
11194    48
11195    46
11196    37
11197    39
11198    38
11199    40
11200    42
11201    35
11202    50
11203    35
11204    38
Name: traveltime, Length: 11199, dtype: int64

In [80]:
norm

array([2266.55640124, 2266.49882418, 2266.26088304, ..., 2258.03068181,
       2253.69050448, 2260.96651015])

In [81]:
df['traveltime']*norm

0        45.0
1        42.0
2        49.0
3        53.0
4        51.0
5        52.0
6        47.0
7        39.0
8        44.0
9        45.0
10       47.0
11       49.0
12       43.0
13       35.0
14       40.0
15       40.0
16       50.0
17       51.0
18       43.0
19       39.0
20       42.0
21       40.0
22       42.0
23       39.0
24       40.0
25       51.0
26       43.0
27       42.0
28       47.0
29       46.0
         ... 
11169    45.0
11170    40.0
11171    47.0
11172    49.0
11173    49.0
11174    50.0
11175    49.0
11176    46.0
11177    55.0
11178    51.0
11179    50.0
11180    49.0
11181    55.0
11182    47.0
11183    46.0
11184    51.0
11185    51.0
11186    44.0
11187    53.0
11188    48.0
11189    46.0
11190    37.0
11191    39.0
11192    38.0
11193    40.0
11194    42.0
11195    35.0
11196    50.0
11197    35.0
11198    38.0
Name: traveltime, Length: 11199, dtype: float64